[project]
name = "dreamnetworking"
version = "0.1.1"
description = "Dream Networking and Automation website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = ["mkdocs-material[imaging]==9.6.20", "mkdocs-rss-plugin>=1.17.1"]
